---
title: "OTB_salinity"
author: "Lilianna"
date: "2025-12-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


import packages and functions
```{r packages, warning=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
library(purrr)
"%ni%" <- Negate("%in%")
library(googlesheets4)
library(patchwork)
library(broom)
library(flextable)
library(kableExtra)
library(growthrates)
library(readr)
library(ggspatial)
library(ggOceanMaps)
library(readxl)
```

```{r}
df <- read_excel("/Users/lilia/Downloads/TB_Phyto _20250508_1014.xlsx")
```

```{r}
library(ggOceanMaps)
coords <- read_sheet("https://docs.google.com/spreadsheets/d/1uMg7J9nv4E8PAOlW-msOi2YNinEexmcY7h_dJc_-OuE/edit?usp=sharing")

bact_geo <- bact_all %>%
  left_join(coords, by = "Station")
station_levels <- paste0("St", 1:10)
coords <- coords %>%
  mutate(Station = factor(Station, levels = station_levels))
bact_geo <- bact_geo %>%
  mutate(Station = factor(Station, levels = station_levels))
# OTB map limits
limits <- c(lon_min = -82.8, lon_max = -82.5, lat_min = 27.6, lat_max = 28.1)

basemap(limits = limits) +
  geom_point(data = coords,
             aes(x = Long, y = Lat, color = Station),
             size = 3) +
  scale_color_viridis_d(option = "turbo") +
  labs(title = "OTB Sampling Stations",
       x = "Longitude", y = "Latitude", color = "Station")


```